# Generated by Django 3.2.6 on 2021-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='policy_agreement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
